#create a grouping sets query
SELECT DIMCOUNTRY.COUNTRY, DIMCATEGORY.CATEGORY, SUM(FACTSALE.AMOUNT) AS TOTAL_SALE
  FROM 
	FACTSALE 
INNER JOIN DIMCOUNTRY 
	ON FACTSALE.COUNTRYID = DIMCOUNTRY.COUNTRYID
INNER JOIN DIMCATEGORY 
	ON FACTSALE.CATEGORYID = DIMCATEGORY.CATEGORYID
  GROUP BY
   GROUPING SETS ( DIMCOUNTRY. COUNTRY, DIMCATEGORY. CATEGORY); 

# create rollup query
SELECT DIMDATE.YEAR, DIMCOUNTRY.COUNTRY, SUM(FACTSALE.AMOUNT)
  FROM 
	FACTSALE 
INNER JOIN DIMDATE 
	ON FACTSALE.DATEID = DIMDATE.DATEID
INNER JOIN DIMCOUNTRY 
	ON FACTSALE.COUNTRYID = DIMCOUNTRY.COUNTRYID
  GROUP BY
   ROLLUP ( DIMDATE.YEAR ,DIMCOUNTRY. COUNTRY); 

# create cube query
SELECT DIMDATE.YEAR, DIMCOUNTRY.COUNTRY, AVG(FACTSALE.AMOUNT)
  FROM 
	FACTSALE 
INNER JOIN DIMDATE 
	ON FACTSALE.DATEID = DIMDATE.DATEID
INNER JOIN DIMCOUNTRY 
	ON FACTSALE.COUNTRYID = DIMCOUNTRY.COUNTRYID
  GROUP BY
   CUBE ( DIMDATE.YEAR ,DIMCOUNTRY. COUNTRY); 



